version: '3'

services:
    nginx:
        container_name : nginx
        build: requirements/nginx
        restart: always
        ports:
            - "443:443"
        volumes:
            - wp:/var/www/html
        networks:
            - intra
        tty: true
    wordpress:
        container_name : wordpress
        build: requirements/wordpress
        restart: always
        volumes:
            - wp:/var/www/html
        expose:
            - "9000"
        networks:
            - intra
        env_file:
            - .env
        tty: true
    mariadb:
        container_name : mariadb
        build: requirements/mariadb
        restart: always
        volumes :
            - db:/var/lib/mysql
        expose:
            - "3306"
        networks:
            - intra
        tty: true
networks:
    intra:
        driver: bridge
volumes:
    db: {}
    wp: {}
